### PR TITLE
Update exp.js

### PR DESCRIPTION
**Pull request by adamgallowayscala**

### CODE REVIEW

**Comment by jrd261** [comment]
AMAZING !!!!!!!!!

**Comment by jrd261** [comment]
Donts forgets tos bumps versions.

**Comment by adamgallowayscala** [comment]
bumped

**Comment by adamgallowayscala** [comment]
unless there are other places?

**Comment by jrd261** [comment]
I think that's it. We clobbered the version bump in the last PR (the old one I just merged) actually but I didn't deploy it yet so we're good. :pizza:

**Pull request merged**
